Remove promisify from event-emitter
neon-bindings/examples pull request #31
Opened 2019-03-25 17:59 UTC by qm3ster

Simplifies the example

Transferred the promisify usage to `async` example instead

Also removed unused dependencies from `package.json`

2019-03-25 18:04 UTC, kjvalencik reviewed
[deleted]

2019-03-25 18:04 UTC, kjvalencik commented on event-emitter/lib/emitter.js
> +    // Start the polling loop on next iteration of the JS event loop to prevent zalgo.
?

2019-03-25 19:44 UTC, qm3ster commented
@kjvalencik I'm glad this will be fixed in core, this is an important usecase for me.
But I think we should provide the best possible solution in the meantime.

Do you think it would be harmful if I added the synchronous fetching of multiple events when available, as I described in the Slack reply thread?

2019-04-06 05:25 UTC, amilajack requested changes
Some small changes but other than that, good stuff! Thanks for the contribution

2019-04-06 05:25 UTC, amilajack commented on event-emitter/lib/emitter.js
> +    // Start the polling loop on next iteration of the JS event loop to prevent zalgo.
Not everyone going through the examples will know what zalgo is. I think we should replace this with something more intuitive.

2019-04-07 15:54 UTC, qm3ster commented on event-emitter/lib/emitter.js
> +    // Start the polling loop on next iteration of the JS event loop to prevent zalgo.
Agreed + I think this change actually isn't necessary the way the example is currently written.

2019-12-08 17:40 UTC, amilajack approved these changes

2019-12-08 18:58 UTC, merged